	/* This file is automatically generated by the version script.
 *				DO NOT EDIT BY HAND OR CHECK-IN                         */

extern int gGetMajorCvedVersionNum();
extern int gGetMinorCvedVersionNum();
extern int gGetMinorExt1CvedVersionNum();
extern int gGetMinorExt2CvedVersionNum();
extern int gGetMinorExt3CvedVersionNum();
