/* This file is automatically generated by the version script.
 *				DO NOT EDIT BY HAND OR CHECK-IN                          */

#define gMAJOR_CVED_VERSION_NUM 650
#define gMINOR_CVED_VERSION_NUM 10822
#define gMINOREXT1_CVED_VERSION_NUM 0
#define gMINOREXT2_CVED_VERSION_NUM 0
#define gMINOREXT3_CVED_VERSION_NUM 0
int gGetMajorCvedVersionNum(){ return gMAJOR_CVED_VERSION_NUM;}
int gGetMinorCvedVersionNum(){ return gMINOR_CVED_VERSION_NUM;}
int gGetMinorExt1CvedVersionNum(){ return gMINOREXT1_CVED_VERSION_NUM;}
int gGetMinorExt2CvedVersionNum(){ return gMINOREXT2_CVED_VERSION_NUM;}
int gGetMinorExt3CvedVersionNum(){ return gMINOREXT3_CVED_VERSION_NUM;}
