/* A Bison parser, made from parser.y
   by GNU bison 1.35.  */

#define YYBISON 1  /* Identify Bison output.  */

# define	LRI_ROADS	500
# define	LRI_LANES	501
# define	LRI_POSITIVE	503
# define	LRI_NEGATIVE	504
# define	LRI_CURLY_OPEN	505
# define	LRI_CURLY_CLOSE	506
# define	LRI_DIRECTION	507
# define	LRI_IDENTIFIER	513
# define	LRI_LAT_CURVES	514
# define	LRI_LATCURVE	515
# define	LRI_LANEWIDTH	516
# define	LRI_ATTR	517
# define	LRI_LONGCURVE	518
# define	LRI_SEMI	519
# define	LRI_INTERSECTIONS	520
# define	LRI_ELEVMAP	521
# define	LRI_BORDER	522
# define	LRI_CRDR	523
# define	LRI_HOLDOFS	524
# define	LRI_CRDR_CURVE	525
# define	LRI_HOLDLINE	526
# define	LRI_HOLDSIGN	527
# define	LRI_EQUALTO	528
# define	LRI_LINES	529
# define	LRI_LFLAG	530
# define	LRI_CRDR_REASON	531
# define	LRI_LSTYLE	532
# define	LRI_REAL	533
# define	LRI_REPOBJS	534
# define	LRI_ALIGNED	535
# define	LRI_OBJECTS	536
# define	LRI_PLANT	537
# define	LRI_ZDOWN	539
# define	LRI_SOLCHECKSUM	540
# define	LRI_HEADER	541
# define	LRI_QUOTED_STRING	542
# define	LRI_COMMENT	543
# define	LRI_ATTR_DICT	544

#line 16 "parser.y"

/*****************************************************************************
 *		THIS FILE IS AUTOMATICALLY GENERATED FROM parser.y
 *		 Version:      $Id: y.tab.c,v 1.2 2012/04/20 21:11:15 iowa\yefeihe Exp $		 
 ****************************************************************************/

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <malloc.h>
#include <math.h>

#include "parser.h"

extern int  yylex(void);
extern int yyerror(const char *);
extern char *gettxt(const char *, const char *);


/*************************************************************************
 *
 * Global storage for the parser
 *
 ****************************************************************************/
THeader         gHeader;
TRoads         *gpRoadList;
TIntersection  *gpInterList;
TElevMap       *gpElevMaps;
TAttrDict      gAttrDict = { 0 };
TLatCurve      *gpLatCurves;

/* objects are not managed by a linked list because we
 * want them to be stored in the order they appear.  So we use
 * an "expanding" array.
 */
TObject        *gpObjects    = NULL;
int             gObjectCount = 0;
int             gObjectSpace = 0;


#line 58 "parser.y"
#ifndef YYSTYPE
typedef union
{
	int      			ival;
	double   			dval;
	char     			*strval;
	unsigned 			uval;
	TLatCurve			latcurvedef;
	TLatCurve*			latcurveptr;
	TLatCpoint			latcpointdef;
	TCurveDef*			curvedefptr;
	TAttribute			attributedef;
	TAttribute*			attributeptr;
	TLaneDef 			lanedef;
	TLaneList			lanelistdef;
	TControlPoint		controlpointdef;
	TControlPoint*  	controlpointptr;
	TCpointList			cpointlistdef;
	TCpointInfo			cpointinfodef;
	TCpointInfo*		cpointinfoptr;
	TLaneWidth			lanewidthdef;
	TLaneWidth*			lanewidthptr;
	TIntersection*     intersectionsptr;
	TElevMap*           elevmapptr;
	TElevMap            elevmap;
	TElevMap2*          elevmap2ptr;
	TElevMap2ListInfo*  elevmap2listInfo;
	TElevInfo           elevinfodef;
	TRoadName*          roadptr;
	TBorderPt           borderptdef;
	TBorder             borderdef;
	TCrdr               crdrdef;
	TCrdr               *crdrdefptr;
	THoldOfs*           holdofsptr;
	THoldOfs            holdofs;
	TCrdrCurveList      crdrcurvelist;
	TCrdrCurve          crdrcurvedef;
	TCrdrLineInfo*      crdrlineinfoptr;
	THoldOfsInfo*       holdofsinfoptr;
	THoldOfsInfo        holdofsinfo;
	TRepObj*            repobjptr;
	TObject             objdef;
} yystype;
# define YYSTYPE yystype
# define YYSTYPE_IS_TRIVIAL 1
#endif
#ifndef YYDEBUG
# define YYDEBUG 0
#endif



#define	YYFINAL		298
#define	YYFLAG		-32768
#define	YYNTBASE	41

/* YYTRANSLATE(YYLEX) -- Bison token number corresponding to YYLEX. */
#define YYTRANSLATE(x) ((unsigned)(x) <= 544 ? yytranslate[x] : 97)

/* YYTRANSLATE[YYLEX] -- Bison token number corresponding to YYLEX. */
static const char yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       3,     4,     2,     5,     6,     7,     8,     9,     2,     2,
       2,     2,     2,    10,    11,    12,    13,    14,    15,    16,
      17,    18,    19,    20,    21,    22,    23,    24,    25,    26,
      27,    28,    29,    30,    31,    32,    33,    34,     2,    35,
      36,    37,    38,    39,    40
};

#if YYDEBUG
static const short yyprhs[] =
{
       0,     0,     6,    11,    17,    23,    29,    34,    35,    38,
      40,    41,    45,    49,    53,    59,    64,    69,    75,    80,
      83,    87,    90,    94,   111,   127,   132,   133,   136,   138,
     144,   151,   154,   155,   158,   160,   167,   170,   172,   175,
     178,   180,   182,   192,   200,   203,   205,   208,   211,   214,
     216,   217,   220,   222,   228,   233,   239,   245,   248,   250,
     259,   263,   266,   269,   271,   281,   289,   299,   309,   312,
     314,   316,   320,   323,   324,   327,   329,   333,   336,   337,
     340,   342,   346,   349,   351,   352,   366,   379,   382,   384,
     391,   396,   400,   401,   404,   406,   411,   417,   418,   421,
     422,   425,   427,   433,   438,   441,   443,   444,   452,   460,
     469,   478,   483,   484,   487,   489
};
static const short yyrhs[] =
{
      42,    45,    66,    91,    94,     0,    42,    45,     1,    91,
       0,    42,     1,    66,    91,    94,     0,    42,    45,    66,
       1,    94,     0,     1,    45,    66,    91,    94,     0,    37,
       7,    43,     8,     0,     0,    43,    44,     0,    44,     0,
       0,    35,    25,    30,     0,    36,    25,    30,     0,    39,
      25,    38,     0,     3,     7,    46,    51,     8,     0,     3,
       7,    51,     8,     0,    11,     7,    47,     8,     0,    47,
      10,     7,    48,     8,     0,    10,     7,    48,     8,     0,
      30,    49,     0,    49,    50,    50,     0,    50,    50,     0,
      30,    30,    30,     0,    51,    10,    10,    10,     7,    55,
      52,     4,     7,    58,     8,    15,     7,    60,     8,     8,
       0,    10,    10,    10,     7,    55,    52,     4,     7,    58,
       8,    15,     7,    60,     8,     8,     0,    31,     7,    53,
       8,     0,     0,    53,    54,     0,    54,     0,    10,    30,
      30,    30,    30,     0,    10,    30,    30,    30,    30,    32,
       0,    14,    56,     0,     0,    56,    57,     0,    57,     0,
      30,    30,    30,    30,    30,    30,     0,    58,    59,     0,
      59,     0,    30,     9,     0,    60,    61,     0,    61,     0,
       1,     0,    64,    30,    30,    30,    30,    30,    30,    62,
      16,     0,    64,    30,    30,    30,    30,    30,    30,     0,
      62,    63,     0,    63,     0,    12,    10,     0,    14,    56,
       0,    13,    65,     0,    10,     0,     0,    65,    30,     0,
      30,     0,    17,     7,    67,    70,     8,     0,    17,     7,
      70,     8,     0,    17,     7,     1,    70,     8,     0,    17,
       7,    67,     1,     8,     0,    67,    68,     0,    68,     0,
      18,    10,    30,    30,    30,     7,    69,     8,     0,    69,
      30,    30,     0,    30,    30,     0,    70,    71,     0,    71,
       0,    10,    73,     7,     3,    72,    77,    80,    74,     8,
       0,    10,    73,     7,    77,    80,    74,     8,     0,    10,
       1,     7,     3,    72,    77,    80,    74,     8,     0,    10,
      73,     7,     3,     1,    77,    80,    74,     8,     0,    72,
      10,     0,    10,     0,    30,     0,    10,    30,    30,     0,
      14,    75,     0,     0,    75,    76,     0,    76,     0,    30,
      30,    30,     0,    19,    78,     0,     0,    78,    79,     0,
      79,     0,    30,    30,    27,     0,    80,    81,     0,    81,
       0,     0,    20,    10,    30,    10,    30,     7,    82,    22,
       7,    85,     8,    88,     8,     0,    20,    10,    30,    10,
      30,     7,    22,     7,    85,     8,    88,     8,     0,    82,
      83,     0,    83,     0,    21,    30,    30,    28,    84,    84,
       0,    23,    25,    30,    30,     0,    24,    25,    10,     0,
       0,    85,    86,     0,    86,     0,    30,    30,    30,    87,
       0,    26,    27,    29,    27,    29,     0,     0,    14,    89,
       0,     0,    89,    90,     0,    90,     0,    30,    30,    30,
      30,    30,     0,    33,     7,    92,     8,     0,    92,    93,
       0,    93,     0,     0,    10,    10,    10,    30,    30,    30,
      30,     0,    10,    10,    10,    30,    30,    34,    30,     0,
      10,    10,    10,    30,    30,    30,    30,    30,     0,    10,
      10,    10,    30,    30,    34,    30,    30,     0,    40,     7,
      95,     8,     0,     0,    95,    96,     0,    96,     0,    10,
      30,     0
};

#endif

#if YYDEBUG
/* YYRLINE[YYN] -- source line where rule number YYN was defined. */
static const short yyrline[] =
{
       0,   182,   185,   191,   197,   203,   211,   214,   218,   223,
     227,   231,   240,   245,   252,   256,   261,   270,   282,   294,
     317,   327,   338,   349,   369,   391,   397,   404,   412,   419,
     433,   450,   456,   464,   473,   483,   497,   504,   513,   526,
     550,   559,   568,   583,   600,   610,   620,   627,   633,   642,
     648,   655,   662,   673,   681,   687,   693,   702,   709,   716,
     732,   753,   765,   772,   780,   794,   806,   813,   823,   833,
     844,   851,   860,   866,   873,   883,   892,   906,   912,   919,
     933,   942,   953,   963,   971,   979,   993,  1010,  1020,  1030,
    1047,  1056,  1063,  1071,  1094,  1106,  1117,  1127,  1134,  1140,
    1147,  1157,  1166,  1184,  1191,  1202,  1212,  1223,  1238,  1252,
    1266,  1282,  1285,  1288,  1291,  1295
};
#endif


#if (YYDEBUG) || defined YYERROR_VERBOSE

/* YYTNAME[TOKEN_NUM] -- String name of the token TOKEN_NUM. */
static const char *const yytname[] =
{
  "$", "error", "$undefined.", "LRI_ROADS", "LRI_LANES", "LRI_POSITIVE", 
  "LRI_NEGATIVE", "LRI_CURLY_OPEN", "LRI_CURLY_CLOSE", "LRI_DIRECTION", 
  "LRI_IDENTIFIER", "LRI_LAT_CURVES", "LRI_LATCURVE", "LRI_LANEWIDTH", 
  "LRI_ATTR", "LRI_LONGCURVE", "LRI_SEMI", "LRI_INTERSECTIONS", 
  "LRI_ELEVMAP", "LRI_BORDER", "LRI_CRDR", "LRI_HOLDOFS", 
  "LRI_CRDR_CURVE", "LRI_HOLDLINE", "LRI_HOLDSIGN", "LRI_EQUALTO", 
  "LRI_LINES", "LRI_LFLAG", "LRI_CRDR_REASON", "LRI_LSTYLE", "LRI_REAL", 
  "LRI_REPOBJS", "LRI_ALIGNED", "LRI_OBJECTS", "LRI_PLANT", "LRI_ZDOWN", 
  "LRI_SOLCHECKSUM", "LRI_HEADER", "LRI_QUOTED_STRING", "LRI_COMMENT", 
  "LRI_ATTR_DICT", "lri", "lri_header", "header_items", "header_item", 
  "roads_list", "lateral_curve_list", "lateral_curve_def", "curve_def", 
  "lat_cpoints_def", "lat_cpoint", "road_def_list", "repeat_objs", 
  "rep_obj_list", "rep_obj", "road_attributes", "attribute_def", 
  "attribute", "road_lanes", "road_lane", "control_points", 
  "control_point", "cpoint_infolist", "cpoint_info", "control_point_name", 
  "width_def", "intersec_defs", "elev_map_list", "elev_map", 
  "elev_map_part", "intersec_list", "intersec", "road_names", "elev_info", 
  "inter_attr_spec", "inter_attr_list", "inter_attr", "border_def", 
  "border_pt_list", "border_pt", "crdr_list", "crdr", "hold_ofs_list", 
  "hold_ofs", "hold_ofs_info", "crdr_curve", "crdr_curve_point", 
  "crdr_line_info", "crdr_attr_spec", "crdr_attr_list", "crdr_attr", 
  "obj_defs", "obj_list", "obj", "attr_dict", "attr_dict_entry_list", 
  "attr_dict_entry", 0
};
#endif

/* YYR1[YYN] -- Symbol number of symbol that rule YYN derives. */
static const short yyr1[] =
{
       0,    41,    41,    41,    41,    41,    42,    42,    43,    43,
      43,    44,    44,    44,    45,    45,    46,    47,    47,    48,
      49,    49,    50,    51,    51,    52,    52,    53,    53,    54,
      54,    55,    55,    56,    56,    57,    58,    58,    59,    60,
      60,    60,    61,    61,    62,    62,    63,    63,    63,    64,
      64,    65,    65,    66,    66,    66,    66,    67,    67,    68,
      69,    69,    70,    70,    71,    71,    71,    71,    72,    72,
      73,    73,    74,    74,    75,    75,    76,    77,    77,    78,
      78,    79,    80,    80,    80,    81,    81,    82,    82,    83,
      84,    84,    84,    85,    85,    86,    87,    87,    88,    88,
      89,    89,    90,    91,    92,    92,    92,    93,    93,    93,
      93,    94,    94,    95,    95,    96
};

/* YYR2[YYN] -- Number of symbols composing right hand side of rule YYN. */
static const short yyr2[] =
{
       0,     5,     4,     5,     5,     5,     4,     0,     2,     1,
       0,     3,     3,     3,     5,     4,     4,     5,     4,     2,
       3,     2,     3,    16,    15,     4,     0,     2,     1,     5,
       6,     2,     0,     2,     1,     6,     2,     1,     2,     2,
       1,     1,     9,     7,     2,     1,     2,     2,     2,     1,
       0,     2,     1,     5,     4,     5,     5,     2,     1,     8,
       3,     2,     2,     1,     9,     7,     9,     9,     2,     1,
       1,     3,     2,     0,     2,     1,     3,     2,     0,     2,
       1,     3,     2,     1,     0,    13,    12,     2,     1,     6,
       4,     3,     0,     2,     1,     4,     5,     0,     2,     0,
       2,     1,     5,     4,     2,     1,     0,     7,     7,     8,
       8,     4,     0,     2,     1,     2
};

/* YYDEFACT[S] -- default rule to reduce with in state S when YYTABLE
   doesn't specify something else to do.  Zero means the default is an
   error. */
static const short yydefact[] =
{
       0,     0,     0,     0,     0,     0,    10,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     9,     0,     0,     0,
       0,     0,     0,     0,     0,     0,   112,     0,     0,     0,
       6,     8,   112,     2,   112,   112,     0,     0,     0,    15,
       0,     0,     0,     0,     0,    58,     0,    63,   106,     0,
       5,    11,    12,    13,     3,     4,     1,     0,     0,     0,
      14,     0,     0,     0,     0,    70,     0,     0,     0,    57,
       0,    54,    62,     0,     0,   105,     0,    32,     0,    16,
       0,     0,    55,     0,     0,    78,     0,    56,    53,     0,
     103,   104,     0,     0,   114,     0,    26,     0,     0,     0,
      32,     0,    71,     0,     0,    84,     0,     0,   115,   111,
     113,     0,    31,    34,     0,     0,     0,    19,     0,    18,
       0,    26,    69,    78,    78,    78,     0,    77,    80,     0,
      73,    83,     0,     0,     0,    33,     0,     0,     0,     0,
      21,    17,     0,    68,    84,    84,    84,     0,    79,     0,
       0,     0,    82,     0,     0,     0,     0,     0,    28,     0,
      22,    20,     0,    73,    73,    73,    81,     0,     0,    72,
      75,    65,     0,     0,     0,     0,     0,     0,    25,    27,
       0,     0,    37,     0,     0,     0,     0,     0,     0,    74,
      61,    59,     0,   107,   108,     0,     0,    38,     0,    36,
       0,    66,    67,    64,     0,    76,    60,   109,   110,    35,
       0,     0,     0,     0,    29,     0,     0,     0,     0,     0,
      88,    30,    41,    49,    50,    40,     0,     0,     0,     0,
       0,    87,     0,    39,     0,    50,     0,     0,     0,    94,
       0,    24,     0,     0,    92,     0,    99,    93,     0,     0,
      23,     0,     0,    92,    97,     0,     0,    99,     0,     0,
       0,    89,     0,    95,     0,    98,   101,    86,     0,     0,
       0,    91,     0,     0,   100,    85,    43,    90,     0,     0,
       0,     0,     0,     0,    45,     0,     0,    46,    52,    48,
      47,    42,    44,    96,   102,    51,     0,     0,     0
};

static const short yydefgoto[] =
{
     296,     3,    15,    16,     5,    22,    59,    98,   117,   118,
      23,   115,   157,   158,    96,   112,   113,   181,   182,   224,
     225,   283,   284,   226,   289,    11,    44,    45,   173,    46,
      47,   123,    66,   151,   169,   170,   105,   127,   128,   130,
     131,   219,   220,   253,   238,   239,   263,   256,   265,   266,
      26,    74,    75,    50,    93,    94
};

static const short yypact[] =
{
       0,     7,    56,    90,   110,   107,   -21,   107,    45,   105,
     120,   -16,   106,   108,   109,    -4,-32768,   -16,   -16,     1,
      61,   121,   119,    84,    42,   123,    98,   111,   112,    94,
  -32768,-32768,    98,-32768,    98,    98,   125,   126,    87,-32768,
     127,   129,     6,   130,    43,-32768,    88,-32768,   133,   137,
  -32768,-32768,-32768,-32768,-32768,-32768,-32768,   138,   139,    91,
  -32768,   140,    92,   141,   117,-32768,   142,   122,   143,-32768,
      95,-32768,-32768,   144,    96,-32768,   145,   146,   128,-32768,
     149,   150,-32768,   156,   131,    10,   132,-32768,-32768,   153,
  -32768,-32768,   134,    99,-32768,   135,   136,   147,   158,   128,
     146,   159,-32768,    49,   151,   148,   152,   154,-32768,-32768,
  -32768,   155,   135,-32768,   163,   167,   157,   147,   147,-32768,
     164,   136,-32768,    46,   160,    46,   161,   151,-32768,   165,
      37,-32768,   166,   162,   168,-32768,   170,   169,   171,   147,
  -32768,-32768,   179,-32768,   148,   148,   148,   172,-32768,   173,
     174,   178,-32768,   175,    39,   176,   177,   100,-32768,   180,
  -32768,-32768,   181,    37,    37,    37,-32768,   183,   182,   174,
  -32768,-32768,   184,     3,   185,   186,   187,   188,-32768,-32768,
     191,    12,-32768,   180,   189,   194,   200,   190,   192,-32768,
  -32768,-32768,   193,   195,   196,   197,   198,-32768,   204,-32768,
      17,-32768,-32768,-32768,   202,-32768,-32768,-32768,-32768,-32768,
     199,   206,   209,    97,   201,    11,   214,   205,   223,   101,
  -32768,-32768,-32768,-32768,   103,-32768,   207,    11,   208,   210,
     224,-32768,   203,-32768,   211,   104,   215,   212,    18,-32768,
     210,-32768,   216,   226,   102,   217,   218,-32768,    19,   219,
  -32768,   220,   225,   102,   213,   221,   228,   218,   222,   227,
     234,-32768,   229,-32768,   230,   221,-32768,-32768,   240,   231,
     232,-32768,   124,   233,-32768,-32768,    64,-32768,   237,   235,
     243,   236,   135,    54,-32768,   238,   239,-32768,-32768,   241,
     135,-32768,-32768,-32768,-32768,-32768,   254,   255,-32768
};

static const short yypgoto[] =
{
  -32768,-32768,-32768,   244,   265,-32768,-32768,    75,-32768,   -94,
     248,    68,-32768,    33,   242,   -88,  -112,    13,  -172,   -32,
    -216,-32768,   -25,-32768,-32768,   113,-32768,   245,-32768,    14,
     -40,   246,-32768,   -84,-32768,   114,   -41,-32768,   247,   -59,
    -125,-32768,    53,    20,    34,  -184,-32768,    21,-32768,    15,
      71,-32768,   249,    40,-32768,   250
};


#define	YYLAST		374


static const short yytable[] =
{
     135,     1,    34,    -7,    30,   152,    72,    63,   233,   199,
       4,   191,   222,   103,    12,    13,    64,    25,    14,   233,
     198,   223,    72,   139,   140,   212,   246,   257,   199,   104,
      72,    12,    13,   192,    25,    14,    65,     2,   152,   152,
     152,   -50,   180,    41,    68,   161,    18,   180,   237,   237,
     124,   150,    42,    42,   247,    62,   143,   129,    70,   122,
      43,    43,    10,     6,   247,   104,   280,   281,   282,   174,
     291,    36,    54,   175,    55,    56,   280,   281,   282,   184,
     185,   186,   144,   145,   146,   163,   164,   165,    32,    33,
      35,     7,    39,     4,    40,    60,    71,    40,    42,    79,
      82,    80,    42,    88,    90,    42,    73,   109,   178,    92,
     156,   232,   243,   223,   223,    20,    21,     9,   217,   218,
      17,    19,   217,   230,    10,   251,   252,    24,    37,    20,
      48,    27,    53,    28,    29,    57,    58,    61,    49,    42,
      67,    51,    52,    73,    76,    77,    78,    84,    83,    85,
      81,    87,    86,   278,    89,    92,    99,   100,    97,   101,
      95,   102,   106,   107,   108,   111,   119,   114,   129,   122,
     136,   137,   141,   153,   120,   149,   159,   116,   135,   104,
     156,   126,   132,   162,   133,   134,   171,   138,   183,   142,
     179,   147,   154,   187,   290,   235,   200,   201,   155,   166,
     197,   160,   202,   167,   168,   172,   176,   177,   203,   213,
     180,   241,   188,   215,   190,   193,   194,   195,   196,   211,
     204,   227,   205,   206,   216,   207,   208,   209,   210,   214,
     229,   240,   255,   221,   250,   228,   267,   234,   236,   262,
     237,   242,   245,   244,   271,   259,   249,   254,   275,   258,
     260,   264,   269,   287,   297,   298,   272,   270,   292,    31,
     273,   276,   277,   279,   285,   286,   288,   293,     8,   294,
      38,   295,   231,   261,   248,     0,     0,     0,   268,     0,
     274,     0,     0,   189,     0,     0,     0,     0,     0,    69,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,    91,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,   121,   110,     0,     0,     0,     0,     0,   125,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,   148
};

static const short yycheck[] =
{
     112,     1,     1,     3,     8,   130,    46,     1,   224,   181,
       3,     8,     1,     3,    35,    36,    10,    33,    39,   235,
       8,    10,    62,   117,   118,     8,     8,     8,   200,    19,
      70,    35,    36,    30,    33,    39,    30,    37,   163,   164,
     165,    30,    30,     1,     1,   139,     1,    30,    30,    30,
       1,    14,    10,    10,   238,    41,    10,    20,    44,    10,
      18,    18,    17,     7,   248,    19,    12,    13,    14,    30,
      16,    10,    32,    34,    34,    35,    12,    13,    14,   163,
     164,   165,   123,   124,   125,   144,   145,   146,    17,    18,
      19,     1,     8,     3,    10,     8,     8,    10,    10,     8,
       8,    10,    10,     8,     8,    10,    10,     8,     8,    10,
      10,     8,     8,    10,    10,    10,    11,     7,    21,    22,
       7,     8,    21,    22,    17,    23,    24,     7,     7,    10,
       7,    25,    38,    25,    25,    10,    10,    10,    40,    10,
      10,    30,    30,    10,     7,     7,     7,    30,     7,     7,
      10,     8,    30,    29,    10,    10,     7,     7,    30,     3,
      14,    30,    30,    10,    30,    30,     8,    31,    20,    10,
       7,     4,     8,     7,    99,    10,     7,    30,   290,    19,
      10,    30,    30,     4,    30,    30,     8,    30,     7,   121,
     157,    30,    30,    10,   282,   227,   183,     8,    30,    27,
       9,    30,     8,    30,    30,    30,    30,    30,     8,     7,
      30,     8,    30,     7,    30,    30,    30,    30,    30,    15,
      30,     7,    30,    30,    15,    30,    30,    30,    30,    30,
       7,     7,    14,    32,     8,    30,     8,    30,    30,    26,
      30,    30,    30,    28,    10,    25,    30,    30,     8,    30,
      25,    30,    30,    10,     0,     0,    27,    30,   283,    15,
      30,    30,    30,    30,    27,    30,    30,    29,     3,    30,
      22,    30,   219,   253,   240,    -1,    -1,    -1,   257,    -1,
     265,    -1,    -1,   169,    -1,    -1,    -1,    -1,    -1,    44,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    74,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,   100,    93,    -1,    -1,    -1,    -1,    -1,   103,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,   127
};
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
#line 3 "C:/Program Files/GnuWin32/share/bison/bison.simple"

/* Skeleton output parser for bison,

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002 Free Software
   Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.  */

/* As a special exception, when this file is copied by Bison into a
   Bison output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison.  */

/* This is the parser code that is written into each bison parser when
   the %semantic_parser declaration is not specified in the grammar.
   It was written by Richard Stallman by simplifying the hairy parser
   used when %semantic_parser is specified.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

#if ! defined (yyoverflow) || defined (YYERROR_VERBOSE)

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# if YYSTACK_USE_ALLOCA
#  define YYSTACK_ALLOC alloca
# else
#  ifndef YYSTACK_USE_ALLOCA
#   if defined (alloca) || defined (_ALLOCA_H)
#    define YYSTACK_ALLOC alloca
#   else
#    ifdef __GNUC__
#     define YYSTACK_ALLOC __builtin_alloca
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's `empty if-body' warning. */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
# else
#  if defined (__STDC__) || defined (__cplusplus)
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   define YYSIZE_T size_t
#  endif
#  define YYSTACK_ALLOC malloc
#  define YYSTACK_FREE free
# endif
#endif /* ! defined (yyoverflow) || defined (YYERROR_VERBOSE) */


#if (! defined (yyoverflow) \
     && (! defined (__cplusplus) \
	 || (YYLTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  short yyss;
  YYSTYPE yyvs;
# if YYLSP_NEEDED
  YYLTYPE yyls;
# endif
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAX (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# if YYLSP_NEEDED
#  define YYSTACK_BYTES(N) \
     ((N) * (sizeof (short) + sizeof (YYSTYPE) + sizeof (YYLTYPE))	\
      + 2 * YYSTACK_GAP_MAX)
# else
#  define YYSTACK_BYTES(N) \
     ((N) * (sizeof (short) + sizeof (YYSTYPE))				\
      + YYSTACK_GAP_MAX)
# endif

/* Copy COUNT objects from FROM to TO.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if 1 < __GNUC__
#   define YYCOPY(To, From, Count) \
      __builtin_memcpy (To, From, (Count) * sizeof (*(From)))
#  else
#   define YYCOPY(To, From, Count)		\
      do					\
	{					\
	  register YYSIZE_T yyi;		\
	  for (yyi = 0; yyi < (Count); yyi++)	\
	    (To)[yyi] = (From)[yyi];		\
	}					\
      while (0)
#  endif
# endif

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack)					\
    do									\
      {									\
	YYSIZE_T yynewbytes;						\
	YYCOPY (&yyptr->Stack, Stack, yysize);				\
	Stack = &yyptr->Stack;						\
	yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAX;	\
	yyptr += yynewbytes / sizeof (*yyptr);				\
      }									\
    while (0)

#endif


#if ! defined (YYSIZE_T) && defined (__SIZE_TYPE__)
# define YYSIZE_T __SIZE_TYPE__
#endif
#if ! defined (YYSIZE_T) && defined (size_t)
# define YYSIZE_T size_t
#endif
#if ! defined (YYSIZE_T)
# if defined (__STDC__) || defined (__cplusplus)
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# endif
#endif
#if ! defined (YYSIZE_T)
# define YYSIZE_T unsigned int
#endif

#define yyerrok		(yyerrstatus = 0)
#define yyclearin	(yychar = YYEMPTY)
#define YYEMPTY		-2
#define YYEOF		0
#define YYACCEPT	goto yyacceptlab
#define YYABORT 	goto yyabortlab
#define YYERROR		goto yyerrlab1
/* Like YYERROR except do call yyerror.  This remains here temporarily
   to ease the transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL		goto yyerrlab
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(Token, Value)					\
do								\
  if (yychar == YYEMPTY && yylen == 1)				\
    {								\
      yychar = (Token);						\
      yylval = (Value);						\
      yychar1 = YYTRANSLATE (yychar);				\
      YYPOPSTACK;						\
      goto yybackup;						\
    }								\
  else								\
    { 								\
      yyerror ("syntax error: cannot back up");			\
      YYERROR;							\
    }								\
while (0)

#define YYTERROR	1
#define YYERRCODE	256


/* YYLLOC_DEFAULT -- Compute the default location (before the actions
   are run).

   When YYLLOC_DEFAULT is run, CURRENT is set the location of the
   first token.  By default, to implement support for ranges, extend
   its range to the last symbol.  */

#ifndef YYLLOC_DEFAULT
# define YYLLOC_DEFAULT(Current, Rhs, N)       	\
   Current.last_line   = Rhs[N].last_line;	\
   Current.last_column = Rhs[N].last_column;
#endif


/* YYLEX -- calling `yylex' with the right arguments.  */

#if YYPURE
# if YYLSP_NEEDED
#  ifdef YYLEX_PARAM
#   define YYLEX		yylex (&yylval, &yylloc, YYLEX_PARAM)
#  else
#   define YYLEX		yylex (&yylval, &yylloc)
#  endif
# else /* !YYLSP_NEEDED */
#  ifdef YYLEX_PARAM
#   define YYLEX		yylex (&yylval, YYLEX_PARAM)
#  else
#   define YYLEX		yylex (&yylval)
#  endif
# endif /* !YYLSP_NEEDED */
#else /* !YYPURE */
# define YYLEX			yylex ()
#endif /* !YYPURE */


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)			\
do {						\
  if (yydebug)					\
    YYFPRINTF Args;				\
} while (0)
/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
#endif /* !YYDEBUG */

/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef	YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   SIZE_MAX < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#if YYMAXDEPTH == 0
# undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif

#ifdef YYERROR_VERBOSE

# ifndef yystrlen
#  if defined (__GLIBC__) && defined (_STRING_H)
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
static YYSIZE_T
#   if defined (__STDC__) || defined (__cplusplus)
yystrlen (const char *yystr)
#   else
yystrlen (yystr)
     const char *yystr;
#   endif
{
  register const char *yys = yystr;

  while (*yys++ != '\0')
    continue;

  return yys - yystr - 1;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined (__GLIBC__) && defined (_STRING_H) && defined (_GNU_SOURCE)
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
static char *
#   if defined (__STDC__) || defined (__cplusplus)
yystpcpy (char *yydest, const char *yysrc)
#   else
yystpcpy (yydest, yysrc)
     char *yydest;
     const char *yysrc;
#   endif
{
  register char *yyd = yydest;
  register const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif
#endif

//#line 315 "C:/Program Files/GnuWin32/share/bison/bison.simple"


/* The user can define YYPARSE_PARAM as the name of an argument to be passed
   into yyparse.  The argument should have type void *.
   It should actually point to an object.
   Grammar actions can access the variable by casting it
   to the proper pointer type.  */

#ifdef YYPARSE_PARAM
# if defined (__STDC__) || defined (__cplusplus)
#  define YYPARSE_PARAM_ARG void *YYPARSE_PARAM
#  define YYPARSE_PARAM_DECL
# else
#  define YYPARSE_PARAM_ARG YYPARSE_PARAM
#  define YYPARSE_PARAM_DECL void *YYPARSE_PARAM;
# endif
#else /* !YYPARSE_PARAM */
# define YYPARSE_PARAM_ARG
# define YYPARSE_PARAM_DECL
#endif /* !YYPARSE_PARAM */

/* Prevent warning if -Wstrict-prototypes.  */
#ifdef __GNUC__
# ifdef YYPARSE_PARAM
int yyparse (void *);
# else
int yyparse (void);
# endif
#endif

/* YY_DECL_VARIABLES -- depending whether we use a pure parser,
   variables are global, or local to YYPARSE.  */

#define YY_DECL_NON_LSP_VARIABLES			\
/* The lookahead symbol.  */				\
int yychar;						\
							\
/* The semantic value of the lookahead symbol. */	\
YYSTYPE yylval;						\
							\
/* Number of parse errors so far.  */			\
int yynerrs;

#if YYLSP_NEEDED
# define YY_DECL_VARIABLES			\
YY_DECL_NON_LSP_VARIABLES			\
						\
/* Location data for the lookahead symbol.  */	\
YYLTYPE yylloc;
#else
# define YY_DECL_VARIABLES			\
YY_DECL_NON_LSP_VARIABLES
#endif


/* If nonreentrant, generate the variables here. */

#if !YYPURE
YY_DECL_VARIABLES
#endif  /* !YYPURE */

int
yyparse (YYPARSE_PARAM_ARG)
     YYPARSE_PARAM_DECL
{
  /* If reentrant, generate the variables here. */
#if YYPURE
  YY_DECL_VARIABLES
#endif  /* !YYPURE */

  register int yystate;
  register int yyn;
  int yyresult;
  /* Number of tokens to shift before error messages enabled.  */
  int yyerrstatus;
  /* Lookahead token as an internal (translated) token number.  */
  int yychar1 = 0;

  /* Three stacks and their tools:
     `yyss': related to states,
     `yyvs': related to semantic values,
     `yyls': related to locations.

     Refer to the stacks thru separate pointers, to allow yyoverflow
     to reallocate them elsewhere.  */

  /* The state stack. */
  short	yyssa[YYINITDEPTH];
  short *yyss = yyssa;
  register short *yyssp;

  /* The semantic value stack.  */
  YYSTYPE yyvsa[YYINITDEPTH];
  YYSTYPE *yyvs = yyvsa;
  register YYSTYPE *yyvsp;

#if YYLSP_NEEDED
  /* The location stack.  */
  YYLTYPE yylsa[YYINITDEPTH];
  YYLTYPE *yyls = yylsa;
  YYLTYPE *yylsp;
#endif

#if YYLSP_NEEDED
# define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
# define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  YYSIZE_T yystacksize = YYINITDEPTH;


  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;
#if YYLSP_NEEDED
  YYLTYPE yyloc;
#endif

  /* When reducing, the number of symbols on the RHS of the reduced
     rule. */
  int yylen;

//  printf("I'm inside yyparse\n");
  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY;		/* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss;
  yyvsp = yyvs;
#if YYLSP_NEEDED
  yylsp = yyls;
#endif
  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed. so pushing a state here evens the stacks.
     */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
	/* Give user a chance to reallocate the stack. Use copies of
	   these so that the &'s don't force the real ones into
	   memory.  */
	YYSTYPE *yyvs1 = yyvs;
	short *yyss1 = yyss;

	/* Each stack pointer address is followed by the size of the
	   data in use in that stack, in bytes.  */
# if YYLSP_NEEDED
	YYLTYPE *yyls1 = yyls;
	/* This used to be a conditional around just the two extra args,
	   but that might be undefined if yyoverflow is a macro.  */
	yyoverflow ("parser stack overflow",
		    &yyss1, yysize * sizeof (*yyssp),
		    &yyvs1, yysize * sizeof (*yyvsp),
		    &yyls1, yysize * sizeof (*yylsp),
		    &yystacksize);
	yyls = yyls1;
# else
	yyoverflow ("parser stack overflow",
		    &yyss1, yysize * sizeof (*yyssp),
		    &yyvs1, yysize * sizeof (*yyvsp),
		    &yystacksize);
# endif
	yyss = yyss1;
	yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyoverflowlab;
# else
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	goto yyoverflowlab;
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;

      {
	short *yyss1 = yyss;
	union yyalloc *yyptr =
	  (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
	if (! yyptr)
	  goto yyoverflowlab;
	YYSTACK_RELOCATE (yyss);
	YYSTACK_RELOCATE (yyvs);
# if YYLSP_NEEDED
	YYSTACK_RELOCATE (yyls);
# endif
# undef YYSTACK_RELOCATE
	if (yyss1 != yyssa)
	  YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;
#if YYLSP_NEEDED
      yylsp = yyls + yysize - 1;
#endif

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
		  (unsigned long int) yystacksize));

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* yyresume: */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (yychar <= 0)		/* This means end of input. */
    {
      yychar1 = 0;
      yychar = YYEOF;		/* Don't call YYLEX any more */

      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yychar1 = YYTRANSLATE (yychar);

#if YYDEBUG
     /* We have to keep this `#if YYDEBUG', since we use variables
	which are defined only if `YYDEBUG' is set.  */
      if (yydebug)
	{
	  YYFPRINTF (stderr, "Next token is %d (%s",
		     yychar, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise
	     meaning of a token, for further debugging info.  */
# ifdef YYPRINT
	  YYPRINT (stderr, yychar, yylval);
# endif
	  YYFPRINTF (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    goto yydefault;

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }
  else if (yyn == 0)
    goto yyerrlab;

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */
  YYDPRINTF ((stderr, "Shifting token %d (%s), ",
	      yychar, yytname[yychar1]));

  /* Discard the token being shifted unless it is eof.  */
  if (yychar != YYEOF)
    yychar = YYEMPTY;

  *++yyvsp = yylval;
#if YYLSP_NEEDED
  *++yylsp = yylloc;
#endif

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  yystate = yyn;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     `$$ = $1'.

     Otherwise, the following line sets YYVAL to the semantic value of
     the lookahead token.  This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];

#if YYLSP_NEEDED
  /* Similarly for the default location.  Let the user run additional
     commands if for instance locations are ranges.  */
  yyloc = yylsp[1-yylen];
  YYLLOC_DEFAULT (yyloc, (yylsp - yylen), yylen);
#endif

#if YYDEBUG
  /* We have to keep this `#if YYDEBUG', since we use variables which
     are defined only if `YYDEBUG' is set.  */
  if (yydebug)
    {
      int yyi;

      YYFPRINTF (stderr, "Reducing via rule %d (line %d), ",
		 yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (yyi = yyprhs[yyn]; yyrhs[yyi] > 0; yyi++)
	YYFPRINTF (stderr, "%s ", yytname[yyrhs[yyi]]);
      YYFPRINTF (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif

  switch (yyn) {

case 2:
#line 186 "parser.y"
{
		fprintf(stderr, "in intersection list definition.\n");
		exit(-1);
	}
    break;
case 3:
#line 192 "parser.y"
{
		fprintf(stderr, "in road list definition.\n");
		exit(-1);
	}
    break;
case 4:
#line 198 "parser.y"
{
		fprintf(stderr, "in object list definition.\n");
		exit(-1);
	}
    break;
case 5:
#line 204 "parser.y"
{
		fprintf(stderr, "in LRI header.\n");
		exit(-1);
	}
    break;
case 8:
#line 220 "parser.y"
{
		}
    break;
case 9:
#line 224 "parser.y"
{
		}
    break;
case 11:
#line 233 "parser.y"
{
			if ( fabs(yyvsp[0].dval) < 0.01 )
				gHeader.zdown = 0;
			else
				gHeader.zdown = 1;
		}
    break;
case 12:
#line 241 "parser.y"
{
			gHeader.solCheckSum = (unsigned int)yyvsp[0].dval;
		}
    break;
case 13:
#line 246 "parser.y"
{
			gHeader.pComment = yyvsp[0].strval;
		}
    break;
case 16:
#line 263 "parser.y"
{
		gpLatCurves = yyvsp[-1].latcurveptr;
		}
    break;
case 17:
#line 273 "parser.y"
{
			TLatCurve* pTemp = calloc(1, sizeof(TLatCurve));

			*pTemp = yyvsp[-1].latcurvedef;
			strncpy (pTemp->curveName, yyvsp[-3].strval, cMAX_WORDLENGTH);
			pTemp->pNext = yyval.latcurveptr;
			yyval.latcurveptr = pTemp;
		}
    break;
case 18:
#line 283 "parser.y"
{
			TLatCurve* pTemp = calloc(1, sizeof(TLatCurve));

			*pTemp = yyvsp[-1].latcurvedef;
			strncpy (pTemp->curveName, yyvsp[-3].strval, cMAX_WORDLENGTH);
			yyval.latcurveptr = pTemp;
		}
    break;
case 19:
#line 296 "parser.y"
{
			TCurveDef *pHead=NULL, *pT;

			yyval.latcurvedef.curveWidth = yyvsp[-1].dval;

			/* the list of points is in $2 but we need */
			/* to flip its direction */

			for ( pT = yyvsp[0].curvedefptr; pT; pT = pT->pNext ) {
				TCurveDef *pNew = calloc(1, sizeof(TLatCurve));

				*pNew = *pT;
				pNew->pNext = pHead;
				pHead = pNew;
			}
			yyval.latcurvedef.pCurveDef = pHead;
		}
    break;
case 20:
#line 319 "parser.y"
{
            TCurveDef* pTemp 	  = calloc(1, sizeof(TCurveDef));
            pTemp->latCpoint1 	  = yyvsp[-1].latcpointdef;
            pTemp->latCpoint2 	  = yyvsp[0].latcpointdef;
            pTemp->pNext          = yyval.curvedefptr;
            yyval.curvedefptr = pTemp;
        }
    break;
case 21:
#line 328 "parser.y"
{
            TCurveDef* pTemp= calloc(1, sizeof(TCurveDef));
            pTemp->latCpoint1 = yyvsp[-1].latcpointdef;
            pTemp->latCpoint2 = yyvsp[0].latcpointdef;
            yyval.curvedefptr = pTemp;
        }
    break;
case 22:
#line 340 "parser.y"
{
			yyval.latcpointdef.height   = yyvsp[-2].dval;
			yyval.latcpointdef.offset   = yyvsp[-1].dval;
			yyval.latcpointdef.material = (int)yyvsp[0].dval;
		}
    break;
case 23:
#line 355 "parser.y"
{
			TRoads* p = calloc(1, sizeof(TRoads));

			strncpy(p->roadName, yyvsp[-14].strval, cMAX_WORDLENGTH);
			strncpy(p->intersection1, yyvsp[-13].strval, cMAX_WORDLENGTH);
			strncpy(p->intersection2, yyvsp[-12].strval, cMAX_WORDLENGTH);
			p->pAttribute   = yyvsp[-10].attributeptr;
			p->pRepObjs     = yyvsp[-9].repobjptr;
			p->lanelist     = yyvsp[-6].lanelistdef;
			p->longitCurve  = yyvsp[-2].cpointlistdef;
			p->pNext        = gpRoadList;
			gpRoadList 	    = p;
		}
    break;
case 24:
#line 374 "parser.y"
{
			TRoads* p = calloc(1, sizeof(TRoads));

			strncpy(p->roadName, yyvsp[-14].strval, cMAX_WORDLENGTH);
			strncpy(p->intersection1, yyvsp[-13].strval, cMAX_WORDLENGTH);
			strncpy(p->intersection2, yyvsp[-12].strval, cMAX_WORDLENGTH);
			p->pAttribute   = yyvsp[-10].attributeptr;
			p->pRepObjs     = yyvsp[-9].repobjptr;
			p->lanelist     = yyvsp[-6].lanelistdef;
			p->longitCurve  = yyvsp[-2].cpointlistdef;
			p->pNext        = gpRoadList;
			gpRoadList 	    = p;
        }
    break;
case 25:
#line 393 "parser.y"
{
			yyval.repobjptr = yyvsp[-1].repobjptr;
		}
    break;
case 26:
#line 398 "parser.y"
{
			yyval.repobjptr = NULL;
		}
    break;
case 27:
#line 406 "parser.y"
{
			/*$$->pNext = $2;*/
			yyvsp[0].repobjptr->pNext = yyval.repobjptr;
			yyval.repobjptr = yyvsp[0].repobjptr;
		}
    break;
case 28:
#line 413 "parser.y"
{
			yyval.repobjptr = yyvsp[0].repobjptr;
		}
    break;
case 29:
#line 421 "parser.y"
{
			TRepObj *pTem = calloc(1, sizeof(TRepObj));

			strcpy(pTem->name, yyvsp[-4].strval);
			pTem->latdist  = yyvsp[-3].dval;
			pTem->start    = yyvsp[-2].dval;
			pTem->period   = yyvsp[-1].dval;
			pTem->end      = yyvsp[0].dval;
			pTem->alligned = 0;
			yyval.repobjptr = pTem;
		}
    break;
case 30:
#line 435 "parser.y"
{
			TRepObj *pTem = calloc(1, sizeof(TRepObj));

			strcpy(pTem->name, yyvsp[-5].strval);
			pTem->latdist  = yyvsp[-4].dval;
			pTem->start    = yyvsp[-3].dval;
			pTem->period   = yyvsp[-2].dval;
			pTem->end      = yyvsp[-1].dval;
			pTem->alligned = 1;
			yyval.repobjptr = pTem;
		}
    break;
case 31:
#line 452 "parser.y"
{
			yyval.attributeptr = yyvsp[0].attributeptr;
		}
    break;
case 32:
#line 457 "parser.y"
{
			yyval.attributeptr = NULL;
		}
    break;
case 33:
#line 466 "parser.y"
{
			TAttribute* pAttr = calloc(1, sizeof(TAttribute));
			*pAttr = yyvsp[0].attributedef;
			pAttr->pNext = yyval.attributeptr;
			yyval.attributeptr = pAttr;
		}
    break;
case 34:
#line 474 "parser.y"
{
			TAttribute* pAttr = calloc(1, sizeof(TAttribute));
            *pAttr = yyvsp[0].attributedef;
			yyval.attributeptr = pAttr;
		}
    break;
case 35:
#line 485 "parser.y"
{
			yyval.attributedef.inum 	= (int)yyvsp[-5].dval;
			yyval.attributedef.laneMask = (int)yyvsp[-4].dval;
			yyval.attributedef.attrNum1	= yyvsp[-3].dval;
			yyval.attributedef.attrNum2	= yyvsp[-2].dval;
			yyval.attributedef.from	    = yyvsp[-1].dval;
			yyval.attributedef.to      	= yyvsp[0].dval;
		}
    break;
case 36:
#line 499 "parser.y"
{
			yyval.lanelistdef.lanes[yyval.lanelistdef.n_lanes] = yyvsp[0].lanedef;
			yyval.lanelistdef.n_lanes++;
		}
    break;
case 37:
#line 505 "parser.y"
{
			yyval.lanelistdef.n_lanes  = 1;
			yyval.lanelistdef.lanes[0] = yyvsp[0].lanedef;
		}
    break;
case 38:
#line 515 "parser.y"
{
			yyval.lanedef.width = yyvsp[-1].dval;
			if ( yyvsp[0].ival == LRI_POSITIVE )
				yyval.lanedef.direction = 'p';
			else
				yyval.lanedef.direction = 'n';
		}
    break;
case 39:
#line 528 "parser.y"
{
			if (yyval.cpointlistdef.n_cpoints == yyval.cpointlistdef.total_cpoints)
			{
				int newSize;
				TControlPoint* temp;
				newSize = yyval.cpointlistdef.total_cpoints + cINITIAL_CPOINTS;
				temp 	= calloc(newSize, sizeof(TControlPoint));
				memcpy(temp, yyval.cpointlistdef.pCpointList, 
									yyval.cpointlistdef.total_cpoints*sizeof(TControlPoint));
				yyval.cpointlistdef.total_cpoints 			 = newSize;
				free (yyval.cpointlistdef.pCpointList);
				yyval.cpointlistdef.pCpointList 				 = temp;
				yyval.cpointlistdef.pCpointList[yyval.cpointlistdef.n_cpoints] = yyvsp[0].controlpointdef;
				yyval.cpointlistdef.n_cpoints++;
			}
			else
			{
				yyval.cpointlistdef.pCpointList[yyval.cpointlistdef.n_cpoints] = yyvsp[0].controlpointdef;
				yyval.cpointlistdef.n_cpoints++;
			}
		}
    break;
case 40:
#line 551 "parser.y"
{
			yyval.cpointlistdef.pCpointList 	  = (TControlPoint*)calloc(cINITIAL_CPOINTS,
										sizeof(TControlPoint));
			yyval.cpointlistdef.total_cpoints  = cINITIAL_CPOINTS;
			yyval.cpointlistdef.n_cpoints	  = 1;
			yyval.cpointlistdef.pCpointList[0] = yyvsp[0].controlpointdef;
		}
    break;
case 41:
#line 560 "parser.y"
{ 
			puts("Error in definition of control point.\n"); 
			return 1;
		}
    break;
case 42:
#line 571 "parser.y"
{
			if ( yyvsp[-8].strval )
				strncpy(yyval.controlpointdef.cpointName, yyvsp[-8].strval, cMAX_WORDLENGTH);
            yyval.controlpointdef.x           = yyvsp[-7].dval;
            yyval.controlpointdef.y           = yyvsp[-6].dval;
            yyval.controlpointdef.z           = yyvsp[-5].dval;
            yyval.controlpointdef.i           = yyvsp[-4].dval;
            yyval.controlpointdef.j           = yyvsp[-3].dval;
            yyval.controlpointdef.k           = yyvsp[-2].dval;
            yyval.controlpointdef.pCpointInfo = yyvsp[-1].cpointinfoptr;
		}
    break;
case 43:
#line 585 "parser.y"
{
			if ( yyvsp[-6].strval )
				strncpy(yyval.controlpointdef.cpointName, yyvsp[-6].strval, cMAX_WORDLENGTH);
            yyval.controlpointdef.x          	 = yyvsp[-5].dval;
            yyval.controlpointdef.y          	 = yyvsp[-4].dval;
            yyval.controlpointdef.z          	 = yyvsp[-3].dval;
            yyval.controlpointdef.i          	 = yyvsp[-2].dval;
            yyval.controlpointdef.j          	 = yyvsp[-1].dval;
            yyval.controlpointdef.k          	 = yyvsp[0].dval;
            yyval.controlpointdef.pCpointInfo 	 = NULL;
		}
    break;
case 44:
#line 602 "parser.y"
{
			TCpointInfo* pCP = calloc(1, sizeof(TCpointInfo));

			*pCP = yyvsp[0].cpointinfodef;
			pCP->pNext = yyval.cpointinfoptr;
			yyval.cpointinfoptr = pCP;
		}
    break;
case 45:
#line 611 "parser.y"
{
			TCpointInfo* pCP = calloc(1, sizeof(TCpointInfo));

			*pCP = yyvsp[0].cpointinfodef;
			yyval.cpointinfoptr = pCP;
		}
    break;
case 46:
#line 622 "parser.y"
{
			memset(&yyval.cpointinfodef, 0, sizeof(yyval.cpointinfodef));
			strncpy(yyval.cpointinfodef.curveName, yyvsp[0].strval, cMAX_WORDLENGTH);
		}
    break;
case 47:
#line 628 "parser.y"
{
			memset(&yyval.cpointinfodef, 0, sizeof(yyval.cpointinfodef));
			yyval.cpointinfodef.pCpointAttribute = yyvsp[0].attributeptr;
		}
    break;
case 48:
#line 634 "parser.y"
{
			memset(&yyval.cpointinfodef, 0, sizeof(yyval.cpointinfodef));
			yyval.cpointinfodef.cpointWidth = yyvsp[0].lanewidthdef;
		}
    break;
case 49:
#line 644 "parser.y"
{
			yyval.strval = yyvsp[0].strval;
		}
    break;
case 50:
#line 649 "parser.y"
{
			yyval.strval = NULL;
		}
    break;
case 51:
#line 657 "parser.y"
{
			yyval.lanewidthdef.lanewidth[yyval.lanewidthdef.n_lanes] = yyvsp[0].dval;
			yyval.lanewidthdef.n_lanes++;
		}
    break;
case 52:
#line 663 "parser.y"
{
			yyval.lanewidthdef.n_lanes 		= 1;
			yyval.lanewidthdef.lanewidth[0] = yyvsp[0].dval; 
		}
    break;
case 53:
#line 676 "parser.y"
{
			gpElevMaps            = yyvsp[-2].elevmapptr;
			gpInterList 		  = yyvsp[-1].intersectionsptr;
		}
    break;
case 54:
#line 682 "parser.y"
{
			gpElevMaps	 		  = NULL;
			gpInterList 		  = yyvsp[-1].intersectionsptr;
		}
    break;
case 55:
#line 688 "parser.y"
{
			fprintf(stderr, "in elevation map list.\n");
			exit(-1); 
		}
    break;
case 56:
#line 694 "parser.y"
{
			fprintf(stderr, "in intersection list.\n");
			exit(-1); 
		}
    break;
case 57:
#line 704 "parser.y"
{
			yyvsp[0].elevmapptr->pNextElevMap = yyval.elevmapptr;
			yyval.elevmapptr = yyvsp[0].elevmapptr;
		}
    break;
case 58:
#line 710 "parser.y"
{
			yyval.elevmapptr = yyvsp[0].elevmapptr;
		}
    break;
case 59:
#line 719 "parser.y"
{
			yyval.elevmapptr = calloc(1, sizeof(TElevMap));
			strncpy (yyval.elevmapptr->elevMapName, yyvsp[-6].strval, cMAX_WORDLENGTH);
			yyval.elevmapptr->n_rows 		= (int)yyvsp[-5].dval;
			yyval.elevmapptr->n_cols 		= (int)yyvsp[-4].dval;
			yyval.elevmapptr->res          = yyvsp[-3].dval;
			yyval.elevmapptr->pElevMap2 	= yyvsp[-1].elevmap2listInfo->pElevMap2Head;
			yyval.elevmapptr->pNextElevMap  = NULL;
			printf("Processed elevation map %s\n",yyval.elevmapptr->elevMapName);
		}
    break;
case 60:
#line 734 "parser.y"
{
			TElevMap2* pTemp	 = malloc(sizeof(TElevMap2));

			/* add to end of list; list contains at least one item */
			/* we add to the tail of the list because order
			 * is important
			 */
			TElevMap2* pTrav;
			pTrav = yyval.elevmap2listInfo->pElevMap2Tail;

			pTemp->z 			 = yyvsp[-1].dval;
			pTemp->materialRef	 = (int)yyvsp[0].dval;
			pTemp->pNextElevMap2 = NULL;

			pTrav->pNextElevMap2 = pTemp;
			yyval.elevmap2listInfo->pElevMap2Tail = pTemp;
		}
    break;
case 61:
#line 754 "parser.y"
{
			TElevMap2ListInfo* pElevMapListInfo = malloc(sizeof(TElevMap2ListInfo));
			TElevMap2* pTemp	 = malloc(sizeof(TElevMap2));
			pTemp->z 			 = yyvsp[-1].dval;
			pTemp->materialRef	 = (int)yyvsp[0].dval;
			pTemp->pNextElevMap2 = NULL;
			pElevMapListInfo->pElevMap2Head = pTemp;
			pElevMapListInfo->pElevMap2Tail = pTemp;
			yyval.elevmap2listInfo = pElevMapListInfo;
		}
    break;
case 62:
#line 767 "parser.y"
{
			yyvsp[0].intersectionsptr->pNext = yyval.intersectionsptr;
			yyval.intersectionsptr = yyvsp[0].intersectionsptr;
		}
    break;
case 63:
#line 773 "parser.y"
{
			yyval.intersectionsptr = yyvsp[0].intersectionsptr;
		}
    break;
case 64:
#line 783 "parser.y"
{
			yyval.intersectionsptr = calloc(1, sizeof(TIntersection));

			strncpy(yyval.intersectionsptr->name, yyvsp[-8].strval, cMAX_WORDLENGTH);
			yyval.intersectionsptr->elevInfo 		  = yyvsp[-7].elevinfodef;
			yyval.intersectionsptr->pRoadNames 		  = yyvsp[-4].roadptr;
			yyval.intersectionsptr->Border		 	  = yyvsp[-3].borderdef;
			yyval.intersectionsptr->pCrdr 			  = yyvsp[-2].crdrdefptr;
			yyval.intersectionsptr->pAttrs            = yyvsp[-1].attributeptr;
		}
    break;
case 65:
#line 796 "parser.y"
{
			yyval.intersectionsptr = calloc(1, sizeof(TIntersection));

			strncpy(yyval.intersectionsptr->name, yyvsp[-6].strval, cMAX_WORDLENGTH);
			yyval.intersectionsptr->elevInfo 		  = yyvsp[-5].elevinfodef;
			yyval.intersectionsptr->Border		 	  = yyvsp[-3].borderdef;
			yyval.intersectionsptr->pCrdr 			  = yyvsp[-2].crdrdefptr;
			yyval.intersectionsptr->pAttrs            = yyvsp[-1].attributeptr;
		}
    break;
case 66:
#line 808 "parser.y"
{
			fprintf(stderr, "in elevation specification.\n");
			exit(-1);
		}
    break;
case 67:
#line 815 "parser.y"
{
			fprintf(stderr, "in definition of '%s'.\n", yyvsp[-8].strval);
			exit(-1);
		}
    break;
case 68:
#line 825 "parser.y"
{
			TRoadName* pTemp = malloc(sizeof(TRoadName));

			strncpy (pTemp->roadName, yyvsp[0].strval, cMAX_WORDLENGTH);
			pTemp->pNextRoadName = yyval.roadptr;
			yyval.roadptr = pTemp;
		}
    break;
case 69:
#line 834 "parser.y"
{
			TRoadName* pTemp = calloc(1, sizeof(TRoadName));

			strncpy (pTemp->roadName, yyvsp[0].strval, cMAX_WORDLENGTH);
			yyval.roadptr = pTemp;
		}
    break;
case 70:
#line 846 "parser.y"
{
			yyval.elevinfodef.elevMapName[0] = '\0';
			yyval.elevinfodef.height = yyvsp[0].dval;
		}
    break;
case 71:
#line 852 "parser.y"
{
			strncpy (yyval.elevinfodef.elevMapName, yyvsp[-2].strval, cMAX_WORDLENGTH);
			yyval.elevinfodef.xorig = yyvsp[-1].dval;
			yyval.elevinfodef.yorig = yyvsp[0].dval;
		}
    break;
case 72:
#line 862 "parser.y"
{
			yyval.attributeptr = yyvsp[0].attributeptr;
		}
    break;
case 73:
#line 867 "parser.y"
{
			yyval.attributeptr = NULL;
		}
    break;
case 74:
#line 875 "parser.y"
{
			TAttribute *pNew = malloc(sizeof(TAttribute));

			*pNew = yyvsp[0].attributedef;
			pNew->pNext = yyval.attributeptr;
			yyval.attributeptr = pNew;
		}
    break;
case 75:
#line 885 "parser.y"
{
			yyval.attributeptr = malloc(sizeof(TAttribute));
			*yyval.attributeptr = yyvsp[0].attributedef;
		}
    break;
case 76:
#line 894 "parser.y"
{
			yyval.attributedef.inum     = (int)yyvsp[-2].dval;
			yyval.attributedef.laneMask = 0;
			yyval.attributedef.attrNum1 = yyvsp[-1].dval;
			yyval.attributedef.attrNum2 = yyvsp[0].dval;
			yyval.attributedef.from     = -1;
			yyval.attributedef.to       = -2;
			yyval.attributedef.pNext    = NULL;
		}
    break;
case 77:
#line 908 "parser.y"
{
			yyval.borderdef = yyvsp[0].borderdef;
		}
    break;
case 78:
#line 913 "parser.y"
{
			yyval.borderdef.nPts = 0;
		}
    break;
case 79:
#line 921 "parser.y"
{
			if ( yyval.borderdef.nPts == cMAX_BORDER_PTS ) {
				char  err[256];

				fprintf(stderr, "Number of border points exceeds internal "
					"maximum.  Recompile parser \nwith higher value "
					"for cMAX_BORDER_PTS (currently %d).\n", cMAX_BORDER_PTS);
				exit(-1);
			}
			yyval.borderdef.list[yyval.borderdef.nPts++] = yyvsp[0].borderptdef;
		}
    break;
case 80:
#line 934 "parser.y"
{
			yyval.borderdef.nPts = 1;
			yyval.borderdef.list[0] = yyvsp[0].borderptdef;
		}
    break;
case 81:
#line 944 "parser.y"
{
			yyval.borderptdef.borderX = yyvsp[-2].dval;
			yyval.borderptdef.borderY = yyvsp[-1].dval;
			yyval.borderptdef.lflag   = yyvsp[0].ival;
		}
    break;
case 82:
#line 955 "parser.y"
{
			TCrdr *pC = malloc(sizeof(*pC));

			*pC = yyvsp[0].crdrdef;
			pC->pNext = yyval.crdrdefptr;
			yyval.crdrdefptr = pC;
		}
    break;
case 83:
#line 964 "parser.y"
{
			TCrdr *pC = calloc(1, sizeof(*pC));

			*pC = yyvsp[0].crdrdef;
			yyval.crdrdefptr =  pC;
		}
    break;
case 84:
#line 972 "parser.y"
{
			yyval.crdrdefptr = NULL;
		}
    break;
case 85:
#line 983 "parser.y"
{
			strncpy (yyval.crdrdef.roadName1, yyvsp[-11].strval, cMAX_WORDLENGTH);
			yyval.crdrdef.crdrLane1 	  = (int)yyvsp[-10].dval;
			strncpy (yyval.crdrdef.roadName2, yyvsp[-9].strval, cMAX_WORDLENGTH);
			yyval.crdrdef.crdrLane2 	  = (int)yyvsp[-8].dval;
			yyval.crdrdef.pHoldOfs	 	  = yyvsp[-6].holdofsptr;
			yyval.crdrdef.CrdrCurveList  = yyvsp[-3].crdrcurvelist;
			yyval.crdrdef.pAttrs         = yyvsp[-1].attributeptr;
		}
    break;
case 86:
#line 997 "parser.y"
{
			strncpy (yyval.crdrdef.roadName1, yyvsp[-10].strval, cMAX_WORDLENGTH);
			yyval.crdrdef.crdrLane1 	  = (int)yyvsp[-9].dval;
			strncpy (yyval.crdrdef.roadName2, yyvsp[-8].strval, cMAX_WORDLENGTH);
			yyval.crdrdef.crdrLane2 	  = (int)yyvsp[-7].dval;
			yyval.crdrdef.pHoldOfs	 	  = NULL;
			yyval.crdrdef.CrdrCurveList  = yyvsp[-3].crdrcurvelist;
			yyval.crdrdef.pAttrs         = yyvsp[-1].attributeptr;
		}
    break;
case 87:
#line 1012 "parser.y"
{
			THoldOfs *pH = malloc(sizeof(*pH));

			*pH = yyvsp[0].holdofs;
			pH->pNextHoldOfs = yyval.holdofsptr;
			yyval.holdofsptr = pH;
		}
    break;
case 88:
#line 1021 "parser.y"
{
			THoldOfs *pH = calloc(1, sizeof(*pH));

			*pH = yyvsp[0].holdofs;
			yyval.holdofsptr =  pH;
		}
    break;
case 89:
#line 1033 "parser.y"
{
			yyval.holdofs.distance = yyvsp[-4].dval;
			yyval.holdofs.clrnc    = yyvsp[-3].dval;
			strncpy(yyval.holdofs.crdrReason, yyvsp[-2].strval, cMAX_WORDLENGTH);
			if ( yyvsp[-1].holdofsinfo.isLine || yyvsp[-1].holdofsinfo.isSign ) 
				yyval.holdofs.info[0] = yyvsp[-1].holdofsinfo;

			if ( yyvsp[0].holdofsinfo.isLine || yyvsp[0].holdofsinfo.isSign ) 
				yyval.holdofs.info[1] = yyvsp[0].holdofsinfo;
		}
    break;
case 90:
#line 1049 "parser.y"
{
			yyval.holdofsinfo.isLine           = 1;
			yyval.holdofsinfo.isSign           = 0;
			yyval.holdofsinfo.thick 			= yyvsp[0].dval;
			yyval.holdofsinfo.angle 			= yyvsp[0].dval;
		}
    break;
case 91:
#line 1057 "parser.y"
{
			yyval.holdofsinfo.isLine           = 0;
			yyval.holdofsinfo.isSign           = 1;
			strncpy(yyval.holdofsinfo.holdSign, yyvsp[0].strval, cMAX_WORDLENGTH);
		}
    break;
case 92:
#line 1064 "parser.y"
{
			yyval.holdofsinfo.isLine           = 0;
			yyval.holdofsinfo.isSign           = 0;
		}
    break;
case 93:
#line 1073 "parser.y"
{
			if (yyval.crdrcurvelist.n_crdrpts == yyval.crdrcurvelist.total_crdrpts)
            {
				int newSize;
				TCrdrCurve* pTemp;
				newSize = yyval.crdrcurvelist.total_crdrpts + cCRDRPOINTS;
				pTemp   = malloc (newSize*sizeof(TCrdrCurve));
				memcpy (pTemp, yyval.crdrcurvelist.pCrdrCurve, yyval.crdrcurvelist.total_crdrpts*sizeof(TCrdrCurve));
				yyval.crdrcurvelist.total_crdrpts 			  = newSize;
				free (yyval.crdrcurvelist.pCrdrCurve);
				yyval.crdrcurvelist.pCrdrCurve 	  			  = pTemp;
				yyval.crdrcurvelist.pCrdrCurve[yyval.crdrcurvelist.n_crdrpts] = yyvsp[0].crdrcurvedef;
				yyval.crdrcurvelist.n_crdrpts++;
            }
            else
            {
                yyval.crdrcurvelist.pCrdrCurve[yyval.crdrcurvelist.n_crdrpts] = yyvsp[0].crdrcurvedef;
                yyval.crdrcurvelist.n_crdrpts++;
            }
		}
    break;
case 94:
#line 1095 "parser.y"
{
/* type of crdr_curve_point is TCrdrCurve           */
			yyval.crdrcurvelist.pCrdrCurve	  = malloc (cCRDRPOINTS*sizeof(TCrdrCurve));
			yyval.crdrcurvelist.total_crdrpts = cCRDRPOINTS;
			yyval.crdrcurvelist.n_crdrpts	  = 1;
			yyval.crdrcurvelist.pCrdrCurve[0] = yyvsp[0].crdrcurvedef;
		}
    break;
case 95:
#line 1108 "parser.y"
{
			yyval.crdrcurvedef.x 			 = yyvsp[-3].dval;
			yyval.crdrcurvedef.y 			 = yyvsp[-2].dval;
			yyval.crdrcurvedef.width 		 = yyvsp[-1].dval;
			yyval.crdrcurvedef.pCrdrLineInfo = yyvsp[0].crdrlineinfoptr;
		}
    break;
case 96:
#line 1119 "parser.y"
{
			yyval.crdrlineinfoptr = calloc(1, sizeof(TCrdrLineInfo));
			yyval.crdrlineinfoptr->lflag1 = yyvsp[-3].ival;
			strncpy (yyval.crdrlineinfoptr->lstyle1, yyvsp[-2].strval, cMAX_WORDLENGTH);
			yyval.crdrlineinfoptr->lflag2 = yyvsp[-1].ival;
			strncpy (yyval.crdrlineinfoptr->lstyle2, yyvsp[0].strval, cMAX_WORDLENGTH);
		}
    break;
case 97:
#line 1128 "parser.y"
{
			yyval.crdrlineinfoptr = NULL;
		}
    break;
case 98:
#line 1136 "parser.y"
{
			yyval.attributeptr = yyvsp[0].attributeptr;
		}
    break;
case 99:
#line 1141 "parser.y"
{
			yyval.attributeptr = NULL;
		}
    break;
case 100:
#line 1149 "parser.y"
{
			TAttribute *pNew = malloc(sizeof(TAttribute));

			*pNew = yyvsp[0].attributedef;
			pNew->pNext = yyval.attributeptr;
			yyval.attributeptr = pNew;
		}
    break;
case 101:
#line 1159 "parser.y"
{
			yyval.attributeptr = malloc(sizeof(TAttribute));

			*yyval.attributeptr = yyvsp[0].attributedef;
		}
    break;
case 102:
#line 1168 "parser.y"
{
			yyval.attributedef.inum     = (int)yyvsp[-4].dval;
			yyval.attributedef.laneMask = 0;
			yyval.attributedef.attrNum1 = yyvsp[-3].dval;
			yyval.attributedef.attrNum2 = yyvsp[-2].dval;
			yyval.attributedef.from     = yyvsp[-1].dval;
			yyval.attributedef.to       = yyvsp[0].dval;
			yyval.attributedef.pNext    = NULL;
		}
    break;
case 103:
#line 1186 "parser.y"
{
	}
    break;
case 104:
#line 1193 "parser.y"
{
			if ( gObjectCount == gObjectSpace ) {
				gObjectSpace += 200;
				gpObjects = realloc(gpObjects, gObjectSpace * sizeof(TObject));
			}

			gpObjects[gObjectCount++] = yyvsp[0].objdef;
		}
    break;
case 105:
#line 1203 "parser.y"
{
			if ( gObjectCount == gObjectSpace ) {
				gObjectSpace += 200;
				gpObjects = realloc(gpObjects, gObjectSpace * sizeof(TObject));
			}

			gpObjects[gObjectCount++] = yyvsp[0].objdef;
		}
    break;
case 106:
#line 1213 "parser.y"
{
		}
    break;
case 107:
#line 1226 "parser.y"
{
			strcpy(yyval.objdef.type, yyvsp[-6].strval);
			strcpy(yyval.objdef.name, yyvsp[-5].strval);
			strcpy(yyval.objdef.sol, yyvsp[-4].strval);
			yyval.objdef.x     = yyvsp[-3].dval;
			yyval.objdef.y     = yyvsp[-2].dval;
			yyval.objdef.z     = yyvsp[-1].dval;
			yyval.objdef.yaw   = yyvsp[0].dval;
			yyval.objdef.plant = 0;
			yyval.objdef.cigi  = -1;
		}
    break;
case 108:
#line 1240 "parser.y"
{
			strcpy(yyval.objdef.type, yyvsp[-6].strval);
			strcpy(yyval.objdef.name, yyvsp[-5].strval);
			strcpy(yyval.objdef.sol, yyvsp[-4].strval);
			yyval.objdef.x     = yyvsp[-3].dval;
			yyval.objdef.y     = yyvsp[-2].dval;
			yyval.objdef.z     = 0.0;
			yyval.objdef.yaw   = yyvsp[0].dval;
			yyval.objdef.plant = 1;
			yyval.objdef.cigi  = -1;
		}
    break;
case 109:
#line 1254 "parser.y"
{
			strcpy(yyval.objdef.type, yyvsp[-7].strval);
			strcpy(yyval.objdef.name, yyvsp[-6].strval);
			strcpy(yyval.objdef.sol, yyvsp[-5].strval);
			yyval.objdef.x     = yyvsp[-4].dval;
			yyval.objdef.y     = yyvsp[-3].dval;
			yyval.objdef.z     = yyvsp[-2].dval;
			yyval.objdef.yaw   = yyvsp[-1].dval;
			yyval.objdef.plant = 0;
			yyval.objdef.cigi  = (int) yyvsp[0].dval;
		}
    break;
case 110:
#line 1268 "parser.y"
{
			strcpy(yyval.objdef.type, yyvsp[-7].strval);
			strcpy(yyval.objdef.name, yyvsp[-6].strval);
			strcpy(yyval.objdef.sol, yyvsp[-5].strval);
			yyval.objdef.x     = yyvsp[-4].dval;
			yyval.objdef.y     = yyvsp[-3].dval;
			yyval.objdef.z     = 0.0;
			yyval.objdef.yaw   = yyvsp[-1].dval;
			yyval.objdef.plant = 1;
			yyval.objdef.cigi  = (int) yyvsp[0].dval;
		}
    break;
case 115:
#line 1296 "parser.y"
{
			AttrDictEntry *pEntry;
			int i, found=0;

			/* Disallow use of dict entries that are already */
			/*  reserved by cved                             */
			if ((int)yyvsp[0].dval < cCV_NUM_RESERVED_ATTR) {

				fprintf(stderr, "Cannot use reserved attribute id: %d\n", 
					(int)yyvsp[0].dval);
				exit(-1);
			}

			/* allocate space if we run out of the available */
			if ( gAttrDict.nSpace == gAttrDict.nEntries ) {
				gAttrDict.nSpace += 20;
				gAttrDict.pList = (AttrDictEntry *)realloc(
							gAttrDict.pList, gAttrDict.nSpace *
									sizeof(AttrDictEntry));
				if ( gAttrDict.pList == NULL ) {
					fprintf(stderr, "Out of memory\n");
					exit(-1);
				}
			}

			/* if the same entry exists, let the latest overwrite */
			for (i=0; i<gAttrDict.nEntries; i++) {
				if ( !strcmp(yyvsp[-1].strval, gAttrDict.pList[i].pName) ) {
					found = 1;
					pEntry = &gAttrDict.pList[i];
					break;
				}
			}

			if ( !found )  {
				pEntry = &gAttrDict.pList[gAttrDict.nEntries++];
			}
			else {
				free(pEntry->pName);
			}
			pEntry->id = (int)yyvsp[0].dval;
			pEntry->pName = malloc(strlen(yyvsp[-1].strval) + 1);
			strcpy(pEntry->pName, yyvsp[-1].strval);
		}
    break;
}

#line 705 "C:/Program Files/GnuWin32/share/bison/bison.simple"


  yyvsp -= yylen;
  yyssp -= yylen;
#if YYLSP_NEEDED
  yylsp -= yylen;
#endif

#if YYDEBUG
  if (yydebug)
    {
      short *yyssp1 = yyss - 1;
      YYFPRINTF (stderr, "state stack now");
      while (yyssp1 != yyssp)
	YYFPRINTF (stderr, " %d", *++yyssp1);
      YYFPRINTF (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;
#if YYLSP_NEEDED
  *++yylsp = yyloc;
#endif

  /* Now `shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  goto yynewstate;


/*------------------------------------.
| yyerrlab -- here on detecting error |
`------------------------------------*/
yyerrlab:
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;

#ifdef YYERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  YYSIZE_T yysize = 0;
	  char *yymsg;
	  int yyx, yycount;

	  yycount = 0;
	  /* Start YYX at -YYN if negative to avoid negative indexes in
	     YYCHECK.  */
	  for (yyx = yyn < 0 ? -yyn : 0;
	       yyx < (int) (sizeof (yytname) / sizeof (char *)); yyx++)
	    if (yycheck[yyx + yyn] == yyx)
	      yysize += yystrlen (yytname[yyx]) + 15, yycount++;
	  yysize += yystrlen ("parse error, unexpected ") + 1;
	  yysize += yystrlen (yytname[YYTRANSLATE (yychar)]);
	  yymsg = (char *) YYSTACK_ALLOC (yysize);
	  if (yymsg != 0)
	    {
	      char *yyp = yystpcpy (yymsg, "parse error, unexpected ");
	      yyp = yystpcpy (yyp, yytname[YYTRANSLATE (yychar)]);

	      if (yycount < 5)
		{
		  yycount = 0;
		  for (yyx = yyn < 0 ? -yyn : 0;
		       yyx < (int) (sizeof (yytname) / sizeof (char *));
		       yyx++)
		    if (yycheck[yyx + yyn] == yyx)
		      {
			const char *yyq = ! yycount ? ", expecting " : " or ";
			yyp = yystpcpy (yyp, yyq);
			yyp = yystpcpy (yyp, yytname[yyx]);
			yycount++;
		      }
		}
	      yyerror (yymsg);
	      YYSTACK_FREE (yymsg);
	    }
	  else
	    yyerror ("parse error; also virtual memory exhausted");
	}
      else
#endif /* defined (YYERROR_VERBOSE) */
	yyerror ("parse error");
    }
  goto yyerrlab1;


/*--------------------------------------------------.
| yyerrlab1 -- error raised explicitly by an action |
`--------------------------------------------------*/
yyerrlab1:
  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
	 error, discard it.  */

      /* return failure if at end of input */
      if (yychar == YYEOF)
	YYABORT;
      YYDPRINTF ((stderr, "Discarding token %d (%s).\n",
		  yychar, yytname[yychar1]));
      yychar = YYEMPTY;
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */

  yyerrstatus = 3;		/* Each real token shifted decrements this */

  goto yyerrhandle;


/*-------------------------------------------------------------------.
| yyerrdefault -- current state does not do anything special for the |
| error token.                                                       |
`-------------------------------------------------------------------*/
yyerrdefault:
#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */

  /* If its default is to accept any token, ok.  Otherwise pop it.  */
  yyn = yydefact[yystate];
  if (yyn)
    goto yydefault;
#endif


/*---------------------------------------------------------------.
| yyerrpop -- pop the current state because it cannot handle the |
| error token                                                    |
`---------------------------------------------------------------*/
yyerrpop:
  if (yyssp == yyss)
    YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#if YYLSP_NEEDED
  yylsp--;
#endif

#if YYDEBUG
  if (yydebug)
    {
      short *yyssp1 = yyss - 1;
      YYFPRINTF (stderr, "Error: state stack now");
      while (yyssp1 != yyssp)
	YYFPRINTF (stderr, " %d", *++yyssp1);
      YYFPRINTF (stderr, "\n");
    }
#endif

/*--------------.
| yyerrhandle.  |
`--------------*/
yyerrhandle:
  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    goto yyerrdefault;

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    goto yyerrdefault;

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	goto yyerrpop;
      yyn = -yyn;
      goto yyreduce;
    }
  else if (yyn == 0)
    goto yyerrpop;

  if (yyn == YYFINAL)
    YYACCEPT;

  YYDPRINTF ((stderr, "Shifting error token, "));

  *++yyvsp = yylval;
#if YYLSP_NEEDED
  *++yylsp = yylloc;
#endif

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

/*---------------------------------------------.
| yyoverflowab -- parser overflow comes here.  |
`---------------------------------------------*/
yyoverflowlab:
  yyerror ("parser stack overflow");
  yyresult = 2;
  /* Fall through.  */

yyreturn:
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
  return yyresult;
}
#line 1342 "parser.y"

